apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-dep
  labels:
    app: aspnet-core-multi-container-app
spec:
  replicas: 1
  selector: 
    matchLabels:
      component: multi-container
  template:
    metadata: 
      labels:
        component: multi-container
    spec:
      containers:
      - name: cmultiapp
        image: parthatanzu.azurecr.io/multiapp-partha:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-partha   
          
      - name: cmultiapi
        image: parthatanzu.azurecr.io/multiapi-partha:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 81
      imagePullSecrets:
      - name: acr-partha
      
        env:
          - name: ASPNETCORE_URLS
            value: http://+:81
