apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-dotnet
  template:
    metadata:
      labels:  
        app: hello-dotnet
    spec:
      containers:
      - image: tanzucodedept.azurecr.io/hello-partha:v1
        name: hello-dotnet        
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-partha
